accounts/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
#URL for pending contents of user
	url(r'^pending_content$', views.pending_content, name="pending_content"),
#urls to allow user to view and edit only his submitted contents 
	url(r'^pending_content/subsection/(?P<tempsubsec_pk>\d+)$', views.see_tempsubsection, name="see_tempsubsection"),
	url(r'^pending_content/saq/(?P<tempsaq_pk>\d+)$', views.see_tempsaq, name="see_tempsaq"),
	url(r'^pending_content/numerical/(?P<tempnum_pk>\d+)$', views.see_tempnumerical, name="see_tempnumerical"),
	url(r'^pending_content/subsection_image/(?P<tempsubsecimg_pk>\d+)$', views.see_tempsubsection_image, name="see_tempsubsection_image"),
]

cms/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
	#Urls for forms
	url(r'^subject/create/$', views.subject_create, name='subject_create'),
	url(r'^subject/(?P<sub_pk>\d+)/edit$', views.subject_edit, name='subject_edit'),
	url(r'^(?P<sub_slug>[\w-]+)/chapter/create/$', views.chapter_create, name='chapter_create'),
	url(r'^(?P<chap_slug>[\w-]+)/edit$', views.chapter_edit, name='chapter_edit'),
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/create/$', views.subtopic_create, name='subtopic_create'),
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/(?P<subt_pk>\d+)/edit$', views.subtopic_edit, name='subtopic_edit'),

	#url for selection and listing
	url(r'^subjects/$', views.subject_list, name='subject_list'),
	url(r'^subject_select/(?P<sub_pk>\d+)/$', views.subject_select, name='subject_select'),
	url(r'^(?P<chap_slug>[\w-]+)/select/$', views.chapter_select, name='chapter_select'),
	url(r'^(?P<chap_slug>[\w-]+)/saq_list/$', views.saq_list, name='saq_list'),
	url(r'^(?P<chap_slug>[\w-]+)/numerical_list/$', views.numerical_list, name='numerical_list'),
	url(r'^(?P<chap_slug>[\w-]+)/saq/(?P<saq_pk>[\w-]+)/$', views.saq_select, name='saq_select'),
	url(r'^(?P<chap_slug>[\w-]+)/numerical/(?P<num_pk>[\w-]+)/$', views.numerical_select, name='numerical_select'),
	url(r'^(?P<chap_slug>[\w-]+)/(?P<subt_slug>[\w-]+)/$', views.subtopic_select, name='subtopic_select'),

]

xylene/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import (login_view, change_credentials_view, logout_view, change_password_view)
from cms.views import subject_list

urlpatterns = [
    url(r'^$', subject_list, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include("cms.urls", namespace='cms')),
    url(r'^tcms/', include("tempcms.urls", namespace = 'tcms')),
    url(r'^user/', include("accounts.urls", namespace = 'accounts')),
]

urlpatterns += url(r'^login/', login_view, name='login'),
urlpatterns += url(r'^logout/', logout_view, name='logout'),
urlpatterns += url(r'^change_credentials/', change_credentials_view, name='change_credentials'),
urlpatterns += url(r'^change_password/', change_password_view, name='change_password'),

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/forms.py
from django import forms
from .models import Subject, Chapter, Subtopic, SAQ, Numerical, Subsection, SubsectionImage

from pagedown.widgets import PagedownWidget

class SubjectForm(forms.ModelForm):
	class Meta:
		model = Subject
		fields = [
			'subject_name',
			'grade',
			'faculty',
			'poster_image',
		]

class ChapterForm(forms.ModelForm):
	class Meta:
		model = Chapter
		fields = [
			'chapter_serial',
			'chapter_name',
			'section',
			'subject',
			'poster_image',
		]

class SubtopicForm(forms.ModelForm):
	class Meta:
		model = Subtopic
		fields = [
			'subtopic_serial',
			'title',
			'chapter',
			'remarks',
			'poster_image',
		]

	def __init__(self, subject, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['chapter'].queryset = \
		self.fields['chapter'].queryset.filter(subject=subject)

class SubsectionForm(forms.ModelForm):
	content = forms.CharField(widget = PagedownWidget)
	class Meta:
		model = Subsection
		fields = [
			'subsection_serial',
			'title',
			'subtopic',
			'content',
			'remarks',
		]

	def __init__(self, chapter, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subtopic'].queryset = \
		self.fields['subtopic'].queryset.filter(chapter=chapter)

class SAQForm(forms.ModelForm):
	question = forms.CharField(widget=PagedownWidget)
	answer = forms.CharField(widget=PagedownWidget)

	class Meta:
		model = SAQ
		fields = [
			'question_serial',
			'question',
			'answer',
			'important',
			'remarks',
			'subtopic',
			'display_image',
		]

	def __init__(self, chapter, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subtopic'].queryset = \
		self.fields['subtopic'].queryset.filter(chapter=chapter)

class NumericalForm(forms.ModelForm):
	question = forms.CharField(widget=PagedownWidget)
	answer = forms.CharField(widget=PagedownWidget)
	class Meta:
		model = Numerical
		fields = [
			'numerical_serial',
			'question',
			'answer',
			'important',
			'remarks',
			'subtopic',
			'display_image',
		]

	def __init__(self, chapter, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subtopic'].queryset = \
		self.fields['subtopic'].queryset.filter(chapter=chapter)

class SubsectionImageForm(forms.ModelForm):
	class Meta:
		model = SubsectionImage
		fields = [
			'image_serial',
			'image',
			'caption',
			'subsection',
	]
	def __init__(self, subtopic, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subsection'].queryset = \
		self.fields['subsection'].queryset.filter(subtopic=subtopic)

cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
# Create your views here.
from .models import Subject, Chapter, SAQ, Numerical, Subtopic, Subsection, SubsectionImage
from .forms import SubjectForm, ChapterForm, SubtopicForm, SAQForm, NumericalForm, SubsectionForm, SubsectionImageForm
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required

@login_required
def subject_list(request):
	subject_set = Subject.objects.all()
	context = {
		"subjects":subject_set,
	}
	return render(request, "cms/subject_list.html", context)

@login_required
def subject_select(request, sub_pk):
	instance = get_object_or_404(Subject, pk=sub_pk)
	chapter_set = Chapter.objects.filter(subject = instance)
	context = {
		"subject_instance":instance,
		"chapters":chapter_set,
	}
	return render(request, "cms/chapter_list.html", context)

@login_required
def chapter_select(request, chap_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_set = Subtopic.objects.filter(chapter = instance)
	subsection_set = []
	for obj in subtopic_set:
		subsection_set += Subsection.objects.filter(subtopic = obj)

	saq_set = SAQ.objects.filter(chapter = instance)
	numerical_set = Numerical.objects.filter(chapter = instance)
	context = {
		"chapter_instance":instance,
		"subtopics":subtopic_set,
		"subsections":subsection_set,
		"saqs":saq_set,
		"numericals": numerical_set,
	}
	return render(request,"cms/chapter_page.html", context)

@login_required
def saq_list(request, chap_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_set = Subtopic.objects.filter(chapter = instance)
	saq_boolean = True
	saq_set = SAQ.objects.filter(chapter = instance)
	numerical_set = Numerical.objects.filter(chapter = instance)
	context = {
		"subtopics":subtopic_set,
		"chapter_instance":instance,
		"saqs":saq_set,
		"numericals":numerical_set,
		"saq_boolean":saq_boolean,
	}
	return render(request, "cms/saq_list.html", context)

@login_required
def numerical_list(request, chap_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_set = Subtopic.objects.filter(chapter = instance)
	numerical_set = Numerical.objects.filter(chapter = instance)
	saq_set = SAQ.objects.filter(chapter = instance)
	numerical_boolean = True
	context = {
		"subtopics":subtopic_set,
		"chapter_instance":instance,
		"numericals":numerical_set,
		"saqs":saq_set,
		"numerical_boolean":numerical_boolean,
	}
	return render(request, "cms/numerical_list.html", context)

@login_required
def subtopic_select(request, chap_slug, subt_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_set = Subtopic.objects.filter(chapter = instance)
	subtopic_instance = get_object_or_404(Subtopic, slug=subt_slug)
	subsection_set = Subsection.objects.filter(subtopic = subtopic_instance)
	subsection_images_set = SubsectionImage.objects.filter(subtopic = subtopic_instance)

	saq_set = SAQ.objects.filter(chapter = instance)
	numerical_set = Numerical.objects.filter(chapter = instance)

	context = {
		"chapter_instance":instance,
		"subtopics":subtopic_set,
		"subtopic":subtopic_instance,
		"subsections":subsection_set,
		"subsection_images":subsection_images_set,
		"numericals":numerical_set,
		"saqs":saq_set,
	}
	return render(request, "cms/subtopic_detail.html", context)

@login_required
def saq_select(request, chap_slug, saq_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	saq_instance = get_object_or_404(SAQ, slug=saq_slug)
	context = {
		"chapter_instance":instance,
		"saq":saq_instance,
	}
	return render(request, "cms/saq_detail.html", context)

@login_required
def numerical_select(request, chap_slug, num_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	numerical_instance = get_object_or_404(Numerical, slug=num_slug)
	context = {
		"chapter_instance":instance,
		"numerical":numerical_instance,
	}
	return render(request, "cms/numerical_detail.html", context)

#Methods for forms. Creating and editing the content
@login_required
@permission_required('cms.add_subject')
def subject_create(request):
	form = SubjectForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(reverse("cms:subject_list"))

	context = {
		"form":form,
	}
	return render(request, 'cms/subject_form.html', context)

@login_required
@permission_required('cms.change_subject')
def subject_edit(request, sub_pk=None):
	instance = get_object_or_404(Subject, id=sub_pk)
	form = SubjectForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False) 
		instance.save()
		return HttpResponseRedirect(instance.get_subject_select_url())

	context = {
		"instance": instance,
		"form": form,
	}
	return render(request, 'cms/subject_form.html', context)

@login_required
@permission_required('cms.add_chapter')
def chapter_create(request, sub_slug=None):
	subject_instance = get_object_or_404(Subject, slug=sub_slug)
	count = Chapter.objects.filter(subject = subject_instance).count()
	data = {'subject':subject_instance, 'chapter_serial':count+1}
	form = ChapterForm(request.POST or None, request.FILES or None, initial=data)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(instance.subject.get_subject_select_url())

	context = {
		"form":form,
		"subject_instance":subject_instance
	}
	return render(request, 'cms/chapter_form.html', context)

@login_required
@permission_required('cms.change_chapter')
def chapter_edit(request, chap_slug=None):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	form = ChapterForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(instance.get_chapter_select_url())

	context = {
		"form":form, 
		"instance":instance,
	}
	return render(request, 'cms/chapter_form.html', context)

@login_required
@permission_required('cms.add_subtopic')
def subtopic_create(request, chap_slug=None):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	count = Subtopic.objects.filter(chapter = chapter_instance).count()
	data = {'chapter':chapter_instance, 'subtopic_serial':count+1}
	form = SubtopicForm(chapter_instance.subject, request.POST or None, request.FILES or None, initial = data)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(chapter_instance.get_chapter_select_url())

	context = {
		"form":form,
		"chapter_instance":chapter_instance,
	}
	return render(request, 'cms/subtopic_form.html', context)

@login_required
@permission_required('cms.change_subtopic')
def subtopic_edit(request, chap_slug=None, subt_pk=None):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	instance = get_object_or_404(Subtopic, id=subt_pk)
	form = SubtopicForm(chapter_instance.subject, request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(instance.get_subtopic_select_url())

	context = {
		"form":form,
		"subtopic":instance,
		"chapter_instance":chapter_instance,
	}
	return render(request, 'cms/subtopic_form.html', context)

@login_required
@permission_required('cms.add_subsection')
def subsection_create(request, chap_slug=None, subt_pk=None):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_instance = get_object_or_404(Subtopic, id=subt_pk)
	count = Subsection.objects.filter(subtopic = subtopic_instance).count()
	data = {'subtopic':subtopic_instance, 'subsection_serial':count+1}
	form = SubsectionForm(chapter_instance, request.POST or None, initial=data)
	form.chapter = chapter_instance
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(subtopic_instance.get_subtopic_select_url())

	context = {
		"form":form,
		"subtopic_instance":subtopic_instance,
		"chapter_instance":chapter_instance,
	}
	return render(request, 'cms/subsection_form.html', context)

@login_required
@permission_required('cms.change_subsection')
def subsection_edit(request,chap_slug=None, subt_pk=None, subsec_pk=None):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_instance = get_object_or_404(Subtopic, id=subt_pk)
	instance = get_object_or_404(Subsection, id=subsec_pk)
	form = SubsectionForm(chapter_instance, request.POST or None, instance = instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(subtopic_instance.get_subtopic_select_url())

	context = {
		"form":form,
		"instance":instance,
		"subtopic_instance":subtopic_instance,
		"chapter_instance":chapter_instance,
	}

	return render(request, 'cms/subsection_form.html', context)

@login_required
@permission_required('cms.add_subsectionimage')
def subsectionimage_create(request, chap_slug=None, subt_pk=None ):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_instance = get_object_or_404(Subtopic, id=subt_pk)
	count = SubsectionImage.objects.filter(subtopic = subtopic_instance).count()
	data = {'image_serial':count+1}
	form = SubsectionImageForm(subtopic_instance, request.POST or None, request.FILES or None,  initial=data)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.subtopic = subtopic_instance
		instance.save()
		return HttpResponseRedirect(subtopic_instance.get_subtopic_select_url())

	context = {
		"form":form,
		"subtopic_instance":subtopic_instance,
		"chapter_instance":chapter_instance,
	}
	return render(request, 'cms/subsection_image_form.html', context)

@login_required
@permission_required('cms.change_subsectionimage')
def subsectionimage_edit(request,chap_slug=None, subt_pk=None, subsecimg_pk=None):

cms/templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
		<title>Subject lists</title>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'cms/css/base.css' %}">
		{% block headextra %}

		{% endblock headextra %}

	</head>
	<body>
  <!--Loading libraries jquery and bootstrap -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>


	<nav class="navbar navbar-expand-lg navbar-light" id="primary_navbar">
  <a class="navbar-brand" href="{% url 'cms:subject_list' %}"> <img style="max-height: 60px !important;" src="{% static 'cms/images/logo.png' %}" alt="Lamphoo logo"> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cms:subject_list' %}">Subjects <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:pending_content' %}">Pending Contents <span class="sr-only">(current)</span></a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>

  <ul class="nav mr-auto justify-content-center">
     <li class="nav-item "> 
     {% block page_title %}

     {% endblock page_title %}
     </li>
  </ul>

  <ul class="nav justify-content-center">

   </ul>

  </div>
</nav>
{% block secondary-nav %}

{% endblock secondary-nav %}

<div class="all-content">
  {% for message in messages %}
  <div class="alert {{ message.tags }} alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
  {% endfor %}
		{% block content %}
		

		{% endblock content %}
</div>	
	</body>

</html>

cms/templates/chapter_base.html
{% extends 'base.html' %}
{% load static %}

{% block headextra %}
<link rel="stylesheet" type="text/css" href="{% static 'cms/css/chapter_style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">

{% block headmore %}

{% endblock headmore %}

{% endblock headextra %}

{% block secondary-nav %}
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
});
</script>

   <ul class="nav nav-tabs justify-content-center nav-fill" id="myTab" role="tablist">
	  <li class="nav-item">
	    <a class="nav-link" id="home-tab" href="{{chapter_instance.get_chapter_select_url}}" role="tab" aria-controls="home" aria-selected="false">Home</a>
	  </li>
	    {% for subtopic_obj in subtopics %}
		  <li class="nav-item">
		    <a class="nav-link" id="{{subtopic_obj.slug}}" href="{{subtopic_obj.get_subtopic_select_url}}" role="tab" aria-controls="Subtopic_description" aria-selected="false">{{subtopic_obj.title}}</a>
		  </li>
	    {% endfor %}
	 	{% if saqs %}
		  <li class="nav-item">
		    <a class="nav-link" id="saq-tab" href="{{chapter_instance.get_saq_list_url}}" role="tab" aria-controls="saq" aria-selected="false">SAQ</a>
		  </li>
	  	{% endif %}
	  	{% if numericals %}
		  <li class="nav-item">
		    <a class="nav-link" id="numerical-tab" href="{{chapter_instance.get_numerical_list_url}}" role="tab" aria-controls="numerical" aria-selected="false">Numerical</a>
		  </li>
	  	{% endif %}
	</ul>
<script type = text/javascript>
	{% if subtopic %}
		$("#home-tab").removeClass("active");
		$("#{{subtopic.slug}}").addClass("active");
	{% elif numerical_boolean %}
		$("#home-tab").removeClass("active");
		$("#numerical-tab").addClass("active");
	{% elif saq_boolean %}
		$("#home-tab").removeClass("active");
		$("#saq-tab").addClass("active");
	{% else %}
		$("#home-tab").addClass("active");
	{% endif %}
</script>

{% endblock secondary-nav%}