cms/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
	#Urls for forms
	url(r'^subject/create/$', views.subject_create, name='subject_create'),
	url(r'^subject/(?P<sub_pk>\d+)/edit$', views.subject_edit, name='subject_edit'),
	url(r'^(?P<sub_slug>[\w-]+)/chapter/create/$', views.chapter_create, name='chapter_create'),
	url(r'^(?P<chap_slug>[\w-]+)/edit$', views.chapter_edit, name='chapter_edit'),
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/create/$', views.subtopic_create, name='subtopic_create'),
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/(?P<subt_pk>\d+)/edit$', views.subtopic_edit, name='subtopic_edit'),

	#url for selection and listing
	url(r'^subjects/$', views.subject_list, name='subject_list'),
	url(r'^subject_select/(?P<sub_pk>\d+)/$', views.subject_select, name='subject_select'),
	url(r'^(?P<chap_slug>[\w-]+)/select/$', views.chapter_select, name='chapter_select'),
	url(r'^(?P<chap_slug>[\w-]+)/saq_list/$', views.saq_list, name='saq_list'),
	url(r'^(?P<chap_slug>[\w-]+)/numerical_list/$', views.numerical_list, name='numerical_list'),
	url(r'^(?P<chap_slug>[\w-]+)/saq/(?P<saq_pk>[\w-]+)/$', views.saq_select, name='saq_select'),
	url(r'^(?P<chap_slug>[\w-]+)/numerical/(?P<num_pk>[\w-]+)/$', views.numerical_select, name='numerical_select'),
	url(r'^(?P<chap_slug>[\w-]+)/(?P<subt_slug>[\w-]+)/$', views.subtopic_select, name='subtopic_select'),

]

tempcms/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
	#urls for subsection create/edit
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/(?P<subt_pk>\d+)/subsection/create/$', views.tempsubsection_create, name='subsection_create'),
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/(?P<subt_pk>\d+)/subsection/(?P<subsec_pk>\d+)/edit/$', views.tempsubsection_edit, name='subsection_edit'),
	
	#urls for saq create/edit
	url(r'^(?P<chap_slug>[\w-]+)/saq/create$', views.tempsaq_create, name='saq_create'),
	url(r'^(?P<chap_slug>[\w-]+)/saq/(?P<saq_pk>\d+)/edit$', views.tempsaq_edit, name='saq_edit'),
	
	#urls for numerical create/edit
	url(r'^(?P<chap_slug>[\w-]+)/numerical/create$', views.tempnumerical_create, name='numerical_create'),
	url(r'^(?P<chap_slug>[\w-]+)/numerical/(?P<num_pk>\d+)/edit$', views.tempnumerical_edit, name='numerical_edit'),
	
	#urls for subsection image create/edit
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/(?P<subt_pk>\d+)/subsection_image/create/$', views.tempsubsectionimage_create, name='subsection_image_create'),
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/(?P<subt_pk>\d+)/subsection_image/(?P<subsecimg_pk>\d+)/edit/$', views.tempsubsectionimage_edit, name='subsection_image_edit'),

	#url to view items pending for approval
	url(r'^pending/subsections$', views.pending_subsections, name = 'pending_subsections'),
	url(r'^pending/saqs$', views.pending_saqs, name = 'pending_saqs'),
	url(r'^pending/numericals$', views.pending_numericals, name = 'pending_numericals' ),
	url(r'^pending/subsection_images$', views.pending_subsection_images, name = 'pending_subsection_images'),

	#urls to approve pending contents
	url(r'^pending/subsections/(?P<tempsubsec_pk>\d+)/approve$', views.approve_subsection, name = "approve_subsection"),
	url(r'^pending/numericals/(?P<tempnum_pk>\d+)/approve$', views.approve_numerical, name = "approve_numerical"),
	url(r'^pending/saqs/(?P<tempsaq_pk>\d+)/approve$', views.approve_saq, name = "approve_saq"),
	url(r'^pending/subsection_images/(?P<tempsubsecimg_pk>\d+)/approve$', views.approve_subsection_image, name = "approve_subsection_image"),
]

xylene/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import (login_view, change_credentials_view, logout_view, change_password_view)
from cms.views import subject_list

urlpatterns = [
    url(r'^$', subject_list, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include("cms.urls", namespace='cms')),
    url(r'^tcms/', include("tempcms.urls", namespace = 'tcms')),
    url(r'^user/', include("accounts.urls", namespace = 'accounts')),
]

urlpatterns += url(r'^login/', login_view, name='login'),
urlpatterns += url(r'^logout/', logout_view, name='logout'),
urlpatterns += url(r'^change_credentials/', change_credentials_view, name='change_credentials'),
urlpatterns += url(r'^change_password/', change_password_view, name='change_password'),

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

#For slug field
from django.db.models.signals import pre_save
from django.utils.text import slugify

#For imagekit
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill

#Upload path for subject, chapter, subtopic poster images
def poster_upload(instance, filename):
	if isinstance(instance, Subject):
		return '{0}/{1}'.format(instance.subject_name, filename)
	elif isinstance(instance, Chapter):
		return '{0}/{1}/{2}'.format(instance.subject.subject_name, instance.chapter_name, filename)
	elif isinstance(instance, Subtopic):
		return '{0}/{1}/{2}/{3}'.format(instance.chapter.subject.subject_name, instance.chapter.chapter_name, instance.title, filename)

#Upload path for saq, numerical images
def image_upload(instance, filename):
	if isinstance(instance, SAQ):
		return '{0}/{1}/saqs/{2}'.format(instance.chapter.subject.subject_name, instance.chapter.chapter_name, filename)
	elif isinstance(instance, Numerical):
		return '{0}/{1}/numericals/{2}'.format(instance.chapter.subject.subject_name, instance.chapter.chapter_name, filename)

# Create your models here.

class Subject(models.Model):
	subject_name = models.CharField(max_length=120)
	slug = models.SlugField(unique=True, blank=True)
	faculty = models.CharField(max_length = 120, blank=True)
	grade = models.CharField(max_length = 120, blank = True, null=True)

	poster_image = models.ImageField(upload_to = poster_upload, null=True, blank=True,
							width_field = "width_field",
							height_field = "height_field")
	poster_thumbnail = ImageSpecField(source='poster_image',
                                      processors=[ResizeToFill(400, 250)],
                                      format='JPEG',
                                      options={'quality': 100})

	height_field = models.IntegerField(default = 0, blank=True, null=True)
	width_field = models.IntegerField(default = 0, blank=True, null=True)

	poster_text = models.CharField(max_length=300, blank=True)

	def get_subject_select_url(self):
		return reverse("cms:subject_select", kwargs={"sub_pk":self.pk})

	def get_subject_edit_url(self):
		return reverse("cms:subject_edit", kwargs={"sub_pk":self.pk})

	def get_chapter_create_url(self):
		return reverse("cms:chapter_create", kwargs={"sub_slug":self.slug})

	def __str__(self):
		return self.subject_name

class Chapter(models.Model):
	chapter_serial = models.IntegerField(null=False, help_text="Chapter No.")
	slug = models.SlugField(unique=True, blank=True)
	chapter_name = models.CharField(max_length=120)
	section = models.CharField(max_length = 120, blank=True)
	subject = models.ForeignKey('Subject', on_delete=models.SET_NULL, null=True, blank=True)

	poster_image = models.ImageField(upload_to = poster_upload, null=True, blank=True,
							width_field = "width_field",
							height_field = "height_field")

	poster_text = models.CharField(max_length=300, blank=True)
	poster_thumbnail = ImageSpecField(source='poster_image',
                                      processors=[ResizeToFill(400, 250)],
                                      format='JPEG',
                                      options={'quality': 100})

	height_field = models.IntegerField(default = 0, blank=True, null=True)
	width_field = models.IntegerField(default = 0, blank=True, null=True)

	class Meta:
		ordering = ["chapter_serial"]

	def get_subject_select_from_chapter(self):
		""" This function was created to call the subject select url from a chapter instance. """
		subject_instance = self.subject
		return reverse("cms:subject_select", kwargs={"sub_pk":subject_instance.pk})

	def get_chapter_select_url(self):
		return reverse("cms:chapter_select", kwargs={"chap_slug":self.slug})

	def get_saq_list_url(self):
		return reverse("cms:saq_list", kwargs={"chap_slug":self.slug})

	def get_numerical_list_url(self):
		return reverse("cms:numerical_list", kwargs={"chap_slug":self.slug})

	def get_chapter_edit_url(self):
		return reverse("cms:chapter_edit", kwargs={"chap_slug":self.slug})

	def get_subtopic_create_url(self):
		return reverse("cms:subtopic_create", kwargs={"chap_slug":self.slug})

	def get_saq_create_url(self):
		return reverse("tcms:saq_create", kwargs={"chap_slug":self.slug})

	def get_numerical_create_url(self):
		return reverse("tcms:numerical_create", kwargs={"chap_slug":self.slug})


	def __str__(self):
		return self.chapter_name

#content class to contain the detailed material.
class Subtopic(models.Model):
	subtopic_serial = models.IntegerField(null=False)
	slug = models.SlugField(unique=True, blank=True)
	title = models.CharField(max_length=240)
	chapter = models.ForeignKey('Chapter', on_delete=models.SET_NULL, null=True, blank=True)
	remarks = models.CharField(max_length=360, blank=True)

	poster_image = models.ImageField(upload_to = poster_upload, null=True, blank=True,
							width_field = "width_field",
							height_field = "height_field")

	poster_text = models.CharField(max_length=300, blank=True)
	height_field = models.IntegerField(default = 0, blank=True, null=True)
	width_field = models.IntegerField(default = 0, blank=True, null=True)
	poster_thumbnail = ImageSpecField(source='poster_image',
                                      processors=[ResizeToFill(400, 250)],
                                      format='JPEG',
                                      options={'quality': 100})

	class Meta:
		ordering = ["chapter", "subtopic_serial"]

	def get_subtopic_select_url(self):
		return reverse("cms:subtopic_select", kwargs={"chap_slug":self.chapter.slug, "subt_slug":self.slug})

	def get_subtopic_edit_url(self):
		return reverse("cms:subtopic_edit", kwargs={"chap_slug":self.chapter.slug, "subt_pk":self.pk})

	def get_subsection_create_url(self):
		return reverse("tcms:subsection_create", kwargs={"chap_slug":self.chapter.slug, "subt_pk":self.pk})

	def get_subsection_image_create_url(self):
		return reverse("tcms:subsection_image_create", kwargs={"chap_slug":self.chapter.slug, "subt_pk":self.pk})

	def __str__(self):
		return self.title

#Class for each subsection of the subtopic
class Subsection(models.Model):
	subsection_serial = models.IntegerField(null=False)
	title = models.CharField(max_length=360)
	slug = models.SlugField(unique=True, blank=True)
	content = models.TextField()
	subtopic = models.ForeignKey('Subtopic', on_delete=models.CASCADE)
	remarks = models.CharField(max_length=360, blank=True)
	date_created = models.DateField(auto_now=False, auto_now_add=True) #For the date of creation
	date_modified = models.DateField() #For the date of last modification
	#User logs
	created_by = models.ForeignKey(User, on_delete = models.SET_NULL, blank=True, null=True, related_name = 'created_by_subsection')
	last_modified_by = models.ForeignKey(User, on_delete = models.SET_NULL, blank=True, null=True, related_name = 'last_modified_by_subsection')
	approved_by = models.ForeignKey(User, on_delete = models.SET_NULL, blank=True, null=True, related_name = 'approved_by_subsection')

	class Meta:
		ordering = ["subsection_serial"]

	def __str__(self):
		return self.title

	def get_subsection_edit_url(self):
		return reverse("tcms:subsection_edit", kwargs={"chap_slug":self.subtopic.chapter.slug, "subt_pk":self.subtopic.pk, "subsec_pk":self.pk})

#Class for short answer questions
class SAQ(models.Model):
	question_serial = models.IntegerField(null=False)
	slug = models.SlugField(unique=True, blank=True)
	question = models.TextField()
	answer = models.TextField()
	important = models.BooleanField(default = False)
	remarks = models.CharField(max_length=360, blank=True)
	chapter = models.ForeignKey('Chapter', on_delete=models.CASCADE)
	subtopic = models.ForeignKey('Subtopic', on_delete=models.CASCADE, null=True, blank=True)
	date_created = models.DateField(auto_now=False, auto_now_add=True) #For the date of creation
	date_modified = models.DateField() #For the date of last modification
	#User logs
	created_by = models.ForeignKey(User, on_delete = models.SET_NULL, blank=True, null=True, related_name = 'created_by_saq')
	last_modified_by = models.ForeignKey(User, on_delete = models.SET_NULL, blank=True, null=True, related_name = 'last_modified_by_saq')
	approved_by = models.ForeignKey(User, on_delete = models.SET_NULL, blank=True, null=True, related_name = 'approved_by_saq')

	display_image = models.ImageField(upload_to = image_upload, null=True, blank=True,
							width_field = "width_field",
							height_field = "height_field")
	image_caption = models.CharField(max_length=300, blank=True)
	height_field = models.IntegerField(default = 0, blank=True, null=True)
	width_field = models.IntegerField(default = 0, blank=True, null=True)

	class Meta:
		ordering = ["question_serial"]

	def get_saq_select_url(self):
		return reverse("cms:saq_select", kwargs={"chap_slug":self.chapter.slug, "saq_pk":self.pk})

	def get_saq_edit_url(self):
		return reverse("tcms:saq_edit", kwargs={"chap_slug":self.chapter.slug, "saq_pk":self.pk})

	def __str__(self):
		string = "%s" %(self.question_serial)
		return string

#Class for numerical problems
class Numerical(models.Model):
	numerical_serial = models.IntegerField(null=False)
	slug = models.SlugField(unique=True, blank=True)
	question = models.TextField()
	answer = models.TextField()
	important = models.BooleanField(default = False)
	remarks = models.CharField(max_length = 360, blank=True)
	chapter = models.ForeignKey('Chapter', on_delete=models.CASCADE)
	subtopic = models.ForeignKey('Subtopic', on_delete=models.CASCADE, blank=True, null=True)
	date_created = models.DateField(auto_now=False, auto_now_add=True) #For the date of creation
	date_modified = models.DateField() #For the date of last modification
	#User logs
	created_by = models.ForeignKey(User, on_delete = models.SET_NULL, blank=True, null=True, related_name = 'created_by_numerical')

tempcms/forms.py
from django import forms
from .models import TempSubsection, TempSAQ, TempNumerical, TempSubsectionImage

from pagedown.widgets import PagedownWidget

class TempSubsectionForm(forms.ModelForm):
	content = forms.CharField(widget = PagedownWidget)
	class Meta:
		model = TempSubsection
		fields = [
			'subsection_serial',
			'title',
			'subtopic',
			'content',
			'remarks',
		]

	def __init__(self, chapter, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subtopic'].queryset = \
		self.fields['subtopic'].queryset.filter(chapter=chapter)

class TempSAQForm(forms.ModelForm):
	question = forms.CharField(widget=PagedownWidget)
	answer = forms.CharField(widget=PagedownWidget)

	class Meta:
		model = TempSAQ
		fields = [
			'question_serial',
			'question',
			'answer',
			'important',
			'remarks',
			'subtopic',
			'display_image',
			'image_caption',
		]

	def __init__(self, chapter, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subtopic'].queryset = \
		self.fields['subtopic'].queryset.filter(chapter=chapter)

class TempNumericalForm(forms.ModelForm):
	question = forms.CharField(widget=PagedownWidget)
	answer = forms.CharField(widget=PagedownWidget)
	class Meta:
		model = TempNumerical
		fields = [
			'numerical_serial',
			'question',
			'answer',
			'important',
			'remarks',
			'subtopic',
			'display_image',
			'image_caption',
		]

	def __init__(self, chapter, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subtopic'].queryset = \
		self.fields['subtopic'].queryset.filter(chapter=chapter)

class TempSubsectionImageForm(forms.ModelForm):
	class Meta:
		model = TempSubsectionImage
		fields = [
			'image_serial',
			'image',
			'caption',
			'subsection',
	]
	def __init__(self, subtopic, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subsection'].queryset = \
		self.fields['subsection'].queryset.filter(subtopic=subtopic)

tempcms/templates/pending/numerical_approval_form.html
{%extends "base.html"%}
{% load crispy_forms_tags %}

{% block headextra %}
{{ form.media }}
{% endblock headextra %}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{chapter_instance.get_subject_select_from_chapter}}" >{{chapter_instance.subject}} </a> | <a href = "{{chapter_instance.get_chapter_select_url}}" >{{chapter_instance.chapter_name}} </a> | <a href = "{{subtopic_instance.get_subtopic_select_url}}"> {{subtopic_instance}} </a>

{% endblock path %}

{% block content %}
<div class = 'col-sm-6 col-sm-offset-2'>
	<p><small>{{chapter_instance.chapter_name}}</small>
	<small>{{chapter_instance.subject}}</small></p>
	<form method = 'POST' action = '' enctype = 'multipart/form-data'>
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class= 'btn btn-default' name = "approve" value = "Approve"/>
	<input type="submit" class= 'btn btn-default' name = "save" value = "Save"/>
	<input type="submit" class= 'btn btn-default' name = "delete" value = "Delete"/>
	</form>
</div>
{%endblock content %}

tempcms/templates/pending/numericals.html
{% extends 'pending/pending_base.html' %}
{% load markdown_deux_tags %}

{% block content %}
<div class="offset-sm-1 offset-md-1">
	<p>Pending Numericals</p>
	{% for obj in numerical_set %}
		<p><strong>{% ifchanged %} {{obj.chapter}} {% endifchanged %}</strong></p>
		<p class = 'content-markdown'>{{obj.numerical_serial}}. {{obj.question}} <a href="{{obj.get_numerical_approval_url}}"> View details</a></p>
		</hr>

	{%endfor%}
</div>
{% endblock content %}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Pending Content </a>

{% endblock path %}

tempcms/templates/pending/pending_base.html
{% extends 'base.html' %}

{% block secondary-nav %}
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
});
</script>

   <ul class="nav nav-tabs justify-content-center nav-fill" id="myTab" role="tablist">
	  <li class="nav-item">
	    <a class="nav-link active" id="subsections-tab" href="{%url 'tcms:pending_subsections'%}" role="tab" aria-controls="subsections" aria-selected="false">Subsections</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="saqs-tab" href="{%url 'tcms:pending_saqs'%}" role="tab" aria-controls="saqs" aria-selected="false">SAQs</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="numericals-tab" href="{%url 'tcms:pending_numericals'%}" role="tab" aria-controls="numericals" aria-selected="false">Numericals</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="images-tab" href="{% url 'tcms:pending_subsection_images'%}" role="tab" aria-controls="images" aria-selected="false">Images</a>
	  </li>
	</ul>
	<script type = text/javascript>
	{% if saq_boolean %}
		$("#subsections-tab").removeClass("active");
		$("#saqs-tab").addClass("active");
	{% elif numerical_boolean %}
		$("#subsections-tab").removeClass("active");
		$("#numericals-tab").addClass("active");
	{% elif subsection_image_boolean %}
		$("#subsections-tab").removeClass("active");
		$("#images-tab").addClass("active");
	{% endif %}

	</script>
{% endblock secondary-nav%}

tempcms/templates/pending/saq_approval_form.html
{%extends "base.html"%}
{% load crispy_forms_tags %}

{% block headextra %}
{{ form.media }}
{% endblock headextra %}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{chapter_instance.get_subject_select_from_chapter}}" >{{chapter_instance.subject}} </a> | <a href = "{{chapter_instance.get_chapter_select_url}}" >{{chapter_instance.chapter_name}} </a> | <a href = "{{subtopic_instance.get_subtopic_select_url}}"> {{subtopic_instance}} </a>

{% endblock path %}

{% block content %}
<div class = 'col-sm-6 col-sm-offset-2'>
	<p><small>{{chapter_instance.chapter_name}}</small>
	<small>{{chapter_instance.subject}}</small></p>
	<form method = 'POST' action = '' enctype = 'multipart/form-data'>
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class= 'btn btn-default' name = "approve" value = "Approve"/>
	<input type="submit" class= 'btn btn-default' name = "save" value = "Save"/>
	<input type="submit" class= 'btn btn-default' name = "delete" value = "Delete"/>
	</form>
</div>
{%endblock content %}

tempcms/templates/pending/saqs.html
{% extends 'pending/pending_base.html' %}
{% load markdown_deux_tags %}

{% block content %}
<div class="offset-md-1 offset-sm-1">

	<p>Pending Short Answer Questions</p>
	{% for obj in saq_set %}
		<p><strong>{% ifchanged %} {{obj.chapter}} {% endifchanged %}</strong></p>
		<p class = 'content-markdown'>{{obj.question_serial}}. {{obj.question}}
			<a href="{{obj.get_saq_approval_url}}"> View Details </a></p>
		<hr/>

	{%endfor%}
</div>
{% endblock content %}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Pending Content </a>

{% endblock path %}

tempcms/templates/pending/subsection_approval_form.html
{%extends "base.html"%}
{% load crispy_forms_tags %}

{% block headextra %}
{{ form.media }}
{% endblock headextra %}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{chapter_instance.get_subject_select_from_chapter}}" >{{chapter_instance.subject}} </a> | <a href = "{{chapter_instance.get_chapter_select_url}}" >{{chapter_instance.chapter_name}} </a> | <a href = "{{subtopic_instance.get_subtopic_select_url}}"> {{subtopic_instance}} </a>

{% endblock path %}

{% block content %}
<div class = 'col-sm-6 col-sm-offset-2'>
	<p>{{subtopic_instance.title}}</p>
	<p><small>{{chapter_instance.chapter_name}}</small>
	<small>{{chapter_instance.subject}}</small></p>
	<form method = 'POST' action = '' enctype = 'multipart/form-data'>
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class= 'btn btn-default' name = "approve" value = "Approve"/>
	<input type="submit" class= 'btn btn-default' name = "save" value = "Save"/>
	<input type="submit" class= 'btn btn-default' name = "delete" value = "Delete"/>
	</form>
</div>
{%endblock content %}

tempcms/templates/pending/subsection_image_approval_form.html
{%extends "base.html"%}
{% load crispy_forms_tags %}

{% block headextra %}
{{ form.media }}
{% endblock headextra %}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{chapter_instance.get_subject_select_from_chapter}}" >{{chapter_instance.subject}} </a> | <a href = "{{chapter_instance.get_chapter_select_url}}" >{{chapter_instance.chapter_name}} </a> | <a href = "{{subtopic_instance.get_subtopic_select_url}}"> {{subtopic_instance}} </a>

{% endblock path %}

{% block content %}
<div class = 'col-sm-6 col-sm-offset-2'>
	<p>{{subtopic_instance.title}}</p>
	<p><small>{{chapter_instance.chapter_name}}</small>
	<small>{{chapter_instance.subject}}</small></p>
	<form method = 'POST' action = '' enctype = 'multipart/form-data'>
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class= 'btn btn-default' name = "approve" value = "Approve"/>
	<input type="submit" class= 'btn btn-default' name = "save" value = "Save"/>
	<input type="submit" class= 'btn btn-default' name = "delete" value = "Delete"/>
	</form>
</div>
{%endblock content %}

tempcms/templates/pending/subsection_images.html
{% extends 'pending/pending_base.html' %}
<div class="offset-md-1 offset-sm-1">
{% block content %}
	{% load markdown_deux_tags %}
		<h4>Pending Subsection Images</h4>
		{% for obj in subsection_images_set %}
			<p><strong>{% ifchanged %} {{obj.subtopic.chapter}} | {{obj.subsection}} {% endifchanged %}</strong></p>
			<p class = 'content-markdown'>{{obj.image_serial}}. {{obj.caption}} <a href="{{obj.get_subsection_image_approval_url}}"> View details </a></p>
			<hr/>

		{%endfor%}
	{% endblock content %}
</div>
{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Pending Content </a>

{% endblock path %}

tempcms/templates/pending/subsections.html
{% extends 'pending/pending_base.html' %}
{% block content %}
{% load markdown_deux_tags %}
<div class="offset-sm-1 offset-md-1">
	<p>Pending Subsections</p>
	{% for obj in subsection_set %}
		<p><strong>{% ifchanged %} {{obj.subtopic.chapter}} | {{obj.subtopic}} {% endifchanged %}</strong></p>
		<p class = 'content-markdown'>{{obj.subsection_serial}}. {{obj.title}} {{obj.date_modified}}
		<a href="{{obj.get_subsection_approval_url}}"> View Details </a>
		</p>
		<hr/>

	{%endfor%}
</div>
{% endblock content %}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Pending Content </a>

{% endblock path %}