cms/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
	#Urls for forms
	url(r'^subject/create/$', views.subject_create, name='subject_create'),
	url(r'^subject/(?P<sub_pk>\d+)/edit$', views.subject_edit, name='subject_edit'),
	url(r'^(?P<sub_slug>[\w-]+)/chapter/create/$', views.chapter_create, name='chapter_create'),
	url(r'^(?P<chap_slug>[\w-]+)/edit$', views.chapter_edit, name='chapter_edit'),
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/create/$', views.subtopic_create, name='subtopic_create'),
	url(r'^(?P<chap_slug>[\w-]+)/subtopic/(?P<subt_pk>\d+)/edit$', views.subtopic_edit, name='subtopic_edit'),

	#url for selection and listing
	url(r'^subjects/$', views.subject_list, name='subject_list'),
	url(r'^subject_select/(?P<sub_pk>\d+)/$', views.subject_select, name='subject_select'),
	url(r'^(?P<chap_slug>[\w-]+)/select/$', views.chapter_select, name='chapter_select'),
	url(r'^(?P<chap_slug>[\w-]+)/saq_list/$', views.saq_list, name='saq_list'),
	url(r'^(?P<chap_slug>[\w-]+)/numerical_list/$', views.numerical_list, name='numerical_list'),
	url(r'^(?P<chap_slug>[\w-]+)/saq/(?P<saq_pk>[\w-]+)/$', views.saq_select, name='saq_select'),
	url(r'^(?P<chap_slug>[\w-]+)/numerical/(?P<num_pk>[\w-]+)/$', views.numerical_select, name='numerical_select'),
	url(r'^(?P<chap_slug>[\w-]+)/(?P<subt_slug>[\w-]+)/$', views.subtopic_select, name='subtopic_select'),

]

xylene/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import (login_view, change_credentials_view, logout_view, change_password_view)
from cms.views import subject_list

urlpatterns = [
    url(r'^$', subject_list, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include("cms.urls", namespace='cms')),
    url(r'^tcms/', include("tempcms.urls", namespace = 'tcms')),
    url(r'^user/', include("accounts.urls", namespace = 'accounts')),
]

urlpatterns += url(r'^login/', login_view, name='login'),
urlpatterns += url(r'^logout/', logout_view, name='logout'),
urlpatterns += url(r'^change_credentials/', change_credentials_view, name='change_credentials'),
urlpatterns += url(r'^change_password/', change_password_view, name='change_password'),

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/forms.py
from django import forms
from .models import Subject, Chapter, Subtopic, SAQ, Numerical, Subsection, SubsectionImage

from pagedown.widgets import PagedownWidget

class SubjectForm(forms.ModelForm):
	class Meta:
		model = Subject
		fields = [
			'subject_name',
			'grade',
			'faculty',
			'poster_image',
		]

class ChapterForm(forms.ModelForm):
	class Meta:
		model = Chapter
		fields = [
			'chapter_serial',
			'chapter_name',
			'section',
			'subject',
			'poster_image',
		]

class SubtopicForm(forms.ModelForm):
	class Meta:
		model = Subtopic
		fields = [
			'subtopic_serial',
			'title',
			'chapter',
			'remarks',
			'poster_image',
		]

	def __init__(self, subject, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['chapter'].queryset = \
		self.fields['chapter'].queryset.filter(subject=subject)

class SubsectionForm(forms.ModelForm):
	content = forms.CharField(widget = PagedownWidget)
	class Meta:
		model = Subsection
		fields = [
			'subsection_serial',
			'title',
			'subtopic',
			'content',
			'remarks',
		]

	def __init__(self, chapter, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subtopic'].queryset = \
		self.fields['subtopic'].queryset.filter(chapter=chapter)

class SAQForm(forms.ModelForm):
	question = forms.CharField(widget=PagedownWidget)
	answer = forms.CharField(widget=PagedownWidget)

	class Meta:
		model = SAQ
		fields = [
			'question_serial',
			'question',
			'answer',
			'important',
			'remarks',
			'subtopic',
			'display_image',
		]

	def __init__(self, chapter, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subtopic'].queryset = \
		self.fields['subtopic'].queryset.filter(chapter=chapter)

class NumericalForm(forms.ModelForm):
	question = forms.CharField(widget=PagedownWidget)
	answer = forms.CharField(widget=PagedownWidget)
	class Meta:
		model = Numerical
		fields = [
			'numerical_serial',
			'question',
			'answer',
			'important',
			'remarks',
			'subtopic',
			'display_image',
		]

	def __init__(self, chapter, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subtopic'].queryset = \
		self.fields['subtopic'].queryset.filter(chapter=chapter)

class SubsectionImageForm(forms.ModelForm):
	class Meta:
		model = SubsectionImage
		fields = [
			'image_serial',
			'image',
			'caption',
			'subsection',
	]
	def __init__(self, subtopic, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subsection'].queryset = \
		self.fields['subsection'].queryset.filter(subtopic=subtopic)

cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
# Create your views here.
from .models import Subject, Chapter, SAQ, Numerical, Subtopic, Subsection, SubsectionImage
from .forms import SubjectForm, ChapterForm, SubtopicForm, SAQForm, NumericalForm, SubsectionForm, SubsectionImageForm
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required

@login_required
def subject_list(request):
	subject_set = Subject.objects.all()
	context = {
		"subjects":subject_set,
	}
	return render(request, "cms/subject_list.html", context)

@login_required
def subject_select(request, sub_pk):
	instance = get_object_or_404(Subject, pk=sub_pk)
	chapter_set = Chapter.objects.filter(subject = instance)
	context = {
		"subject_instance":instance,
		"chapters":chapter_set,
	}
	return render(request, "cms/chapter_list.html", context)

@login_required
def chapter_select(request, chap_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_set = Subtopic.objects.filter(chapter = instance)
	subsection_set = []
	for obj in subtopic_set:
		subsection_set += Subsection.objects.filter(subtopic = obj)

	saq_set = SAQ.objects.filter(chapter = instance)
	numerical_set = Numerical.objects.filter(chapter = instance)
	context = {
		"chapter_instance":instance,
		"subtopics":subtopic_set,
		"subsections":subsection_set,
		"saqs":saq_set,
		"numericals": numerical_set,
	}
	return render(request,"cms/chapter_page.html", context)

@login_required
def saq_list(request, chap_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_set = Subtopic.objects.filter(chapter = instance)
	saq_boolean = True
	saq_set = SAQ.objects.filter(chapter = instance)
	numerical_set = Numerical.objects.filter(chapter = instance)
	context = {
		"subtopics":subtopic_set,
		"chapter_instance":instance,
		"saqs":saq_set,
		"numericals":numerical_set,
		"saq_boolean":saq_boolean,
	}
	return render(request, "cms/saq_list.html", context)

@login_required
def numerical_list(request, chap_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_set = Subtopic.objects.filter(chapter = instance)
	numerical_set = Numerical.objects.filter(chapter = instance)
	saq_set = SAQ.objects.filter(chapter = instance)
	numerical_boolean = True
	context = {
		"subtopics":subtopic_set,
		"chapter_instance":instance,
		"numericals":numerical_set,
		"saqs":saq_set,
		"numerical_boolean":numerical_boolean,
	}
	return render(request, "cms/numerical_list.html", context)

@login_required
def subtopic_select(request, chap_slug, subt_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_set = Subtopic.objects.filter(chapter = instance)
	subtopic_instance = get_object_or_404(Subtopic, slug=subt_slug)
	subsection_set = Subsection.objects.filter(subtopic = subtopic_instance)
	subsection_images_set = SubsectionImage.objects.filter(subtopic = subtopic_instance)

	saq_set = SAQ.objects.filter(chapter = instance)
	numerical_set = Numerical.objects.filter(chapter = instance)

	context = {
		"chapter_instance":instance,
		"subtopics":subtopic_set,
		"subtopic":subtopic_instance,
		"subsections":subsection_set,
		"subsection_images":subsection_images_set,
		"numericals":numerical_set,
		"saqs":saq_set,
	}
	return render(request, "cms/subtopic_detail.html", context)

@login_required
def saq_select(request, chap_slug, saq_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	saq_instance = get_object_or_404(SAQ, slug=saq_slug)
	context = {
		"chapter_instance":instance,
		"saq":saq_instance,
	}
	return render(request, "cms/saq_detail.html", context)

@login_required
def numerical_select(request, chap_slug, num_slug):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	numerical_instance = get_object_or_404(Numerical, slug=num_slug)
	context = {
		"chapter_instance":instance,
		"numerical":numerical_instance,
	}
	return render(request, "cms/numerical_detail.html", context)

#Methods for forms. Creating and editing the content
@login_required
@permission_required('cms.add_subject')
def subject_create(request):
	form = SubjectForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(reverse("cms:subject_list"))

	context = {
		"form":form,
	}
	return render(request, 'cms/subject_form.html', context)

@login_required
@permission_required('cms.change_subject')
def subject_edit(request, sub_pk=None):
	instance = get_object_or_404(Subject, id=sub_pk)
	form = SubjectForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False) 
		instance.save()
		return HttpResponseRedirect(instance.get_subject_select_url())

	context = {
		"instance": instance,
		"form": form,
	}
	return render(request, 'cms/subject_form.html', context)

@login_required
@permission_required('cms.add_chapter')
def chapter_create(request, sub_slug=None):
	subject_instance = get_object_or_404(Subject, slug=sub_slug)
	count = Chapter.objects.filter(subject = subject_instance).count()
	data = {'subject':subject_instance, 'chapter_serial':count+1}
	form = ChapterForm(request.POST or None, request.FILES or None, initial=data)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(instance.subject.get_subject_select_url())

	context = {
		"form":form,
		"subject_instance":subject_instance
	}
	return render(request, 'cms/chapter_form.html', context)

@login_required
@permission_required('cms.change_chapter')
def chapter_edit(request, chap_slug=None):
	instance = get_object_or_404(Chapter, slug=chap_slug)
	form = ChapterForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(instance.get_chapter_select_url())

	context = {
		"form":form, 
		"instance":instance,
	}
	return render(request, 'cms/chapter_form.html', context)

@login_required
@permission_required('cms.add_subtopic')
def subtopic_create(request, chap_slug=None):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	count = Subtopic.objects.filter(chapter = chapter_instance).count()
	data = {'chapter':chapter_instance, 'subtopic_serial':count+1}
	form = SubtopicForm(chapter_instance.subject, request.POST or None, request.FILES or None, initial = data)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(chapter_instance.get_chapter_select_url())

	context = {
		"form":form,
		"chapter_instance":chapter_instance,
	}
	return render(request, 'cms/subtopic_form.html', context)

@login_required
@permission_required('cms.change_subtopic')
def subtopic_edit(request, chap_slug=None, subt_pk=None):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	instance = get_object_or_404(Subtopic, id=subt_pk)
	form = SubtopicForm(chapter_instance.subject, request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(instance.get_subtopic_select_url())

	context = {
		"form":form,
		"subtopic":instance,
		"chapter_instance":chapter_instance,
	}
	return render(request, 'cms/subtopic_form.html', context)

@login_required
@permission_required('cms.add_subsection')
def subsection_create(request, chap_slug=None, subt_pk=None):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_instance = get_object_or_404(Subtopic, id=subt_pk)
	count = Subsection.objects.filter(subtopic = subtopic_instance).count()
	data = {'subtopic':subtopic_instance, 'subsection_serial':count+1}
	form = SubsectionForm(chapter_instance, request.POST or None, initial=data)
	form.chapter = chapter_instance
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(subtopic_instance.get_subtopic_select_url())

	context = {
		"form":form,
		"subtopic_instance":subtopic_instance,
		"chapter_instance":chapter_instance,
	}
	return render(request, 'cms/subsection_form.html', context)

@login_required
@permission_required('cms.change_subsection')
def subsection_edit(request,chap_slug=None, subt_pk=None, subsec_pk=None):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_instance = get_object_or_404(Subtopic, id=subt_pk)
	instance = get_object_or_404(Subsection, id=subsec_pk)
	form = SubsectionForm(chapter_instance, request.POST or None, instance = instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return HttpResponseRedirect(subtopic_instance.get_subtopic_select_url())

	context = {
		"form":form,
		"instance":instance,
		"subtopic_instance":subtopic_instance,
		"chapter_instance":chapter_instance,
	}

	return render(request, 'cms/subsection_form.html', context)

@login_required
@permission_required('cms.add_subsectionimage')
def subsectionimage_create(request, chap_slug=None, subt_pk=None ):
	chapter_instance = get_object_or_404(Chapter, slug=chap_slug)
	subtopic_instance = get_object_or_404(Subtopic, id=subt_pk)
	count = SubsectionImage.objects.filter(subtopic = subtopic_instance).count()
	data = {'image_serial':count+1}
	form = SubsectionImageForm(subtopic_instance, request.POST or None, request.FILES or None,  initial=data)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.subtopic = subtopic_instance
		instance.save()
		return HttpResponseRedirect(subtopic_instance.get_subtopic_select_url())

	context = {
		"form":form,
		"subtopic_instance":subtopic_instance,
		"chapter_instance":chapter_instance,
	}
	return render(request, 'cms/subsection_image_form.html', context)

@login_required
@permission_required('cms.change_subsectionimage')
def subsectionimage_edit(request,chap_slug=None, subt_pk=None, subsecimg_pk=None):

cms/templates/cms/chapter_form.html
{%extends "base.html"%}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{subject_instance.get_subject_select_url}}" >{{subject_instance}} </a>

{% endblock path %}

{% block content %}
{% load crispy_forms_tags %}
<div class = 'col-sm-6 col-sm-offset-2'>
	{{subject_instance.subject_name}}
	<form method = 'POST' action = '' enctype = 'multipart/form-data'>
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class= 'btn btn-default' value = "Okay"/>
	</form>
</div>
{%endblock content %}

cms/templates/cms/chapter_list.html
{% extends 'base.html' %}
{% load static %}

{% block headextra %}
	<link rel="stylesheet" type="text/css" href="{% static 'cms/css/chapter_list_style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">
{% endblock headextra %}

{% block content %}
<div class="document">
	<div class="subject-top">
	<small><a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{subject_instance.get_subject_select_url}}" >{{subject_instance}} </a></small>

		<h1 class="heading"> {{subject_instance}} <a class="edit-link" href="{{subject_instance.get_subject_edit_url}}" >Edit</a></h1>
		<a href="{{subject_instance.get_chapter_create_url}}">Create chapter</a>
		<hr/>
	</div>
	<div class="card-deck">
		{%for obj in chapters%}
		  <div class="col-md-3 col-sm-6">
		    <div class="card mb-3" style="height: 300px;">
					{%if obj.poster_image %}
		    	<a href="{{obj.get_chapter_select_url}}" > <img class="card-img-top" src="{{obj.poster_thumbnail.url}}" alt="Card image cap"> </a>
					{% endif %}
					<div class="card-body">
		        <a href="{{obj.get_chapter_select_url}}" > <strong class="card-title heading"> {{obj.chapter_serial}}. {{obj.chapter_name}}</strong> </a>
		        <p class="card-text">{{obj.poster_text}}</p>
		      </div>
		    </div>
		  </div>
		{% endfor %}
	</div>
</div>
{% endblock content %}

cms/templates/cms/chapter_page.html
{% extends 'chapter_base.html' %}
{% load static %}

{% block headmore %}
	<link rel="stylesheet" type="text/css" href="{% static 'cms/css/chapter_page_style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">
{% endblock headmore %}

{%block content%}
<div class = "document subtopic-list">
	<div class="chapter-page-top">
		<small><div class="path">
			Path: <a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{chapter_instance.get_subject_select_from_chapter}}" >{{chapter_instance.subject}} </a> | <a href = "{{chapter_instance.get_chapter_select_url}}" >{{chapter_instance.chapter_name}} </a>
		</div></small>
		<h1 class = "heading">{{chapter_instance.chapter_serial}}. {{chapter_instance.chapter_name}}
			<a class="edit-link" href={{chapter_instance.get_chapter_edit_url}}>Edit</a>
		</h1>
		<p><a href="{{chapter_instance.get_subtopic_create_url}}">Create subtopic</a> |
		<a href="{{chapter_instance.get_saq_create_url}}">Add SAQs</a> |
		<a href="{{chapter_instance.get_numerical_create_url}}">Add Numericals</a></p>
		<hr/>
	</div>
	<div class="card-deck">
		{%for obj in subtopics%}
		  <div class="col-md-3 col-sm-4">
		    <div class="card mb-3" style="height: 250px;">
					{% if obj.poster_image %}
		    	<a href="{{obj.get_subtopic_select_url}}"> <img class="card-img-top" src="{{obj.poster_thumbnail.url}}" alt="Card image cap"> </a>
					{% endif %}
					<div class="card-body">
		        <a href="{{obj.get_subtopic_select_url}}"> <strong class="heading card-title">{{obj.subtopic_serial}}. {{obj.title}}</strong> </a>
		        <p class="card-text">{{obj.poster_text}}</p>
		      </div>
		    </div>
		  </div>
		{% endfor %}
		{% if saqs %}
		<div class="col-md-3 col-sm-4">
		    <div class="card mb-3" style="height: 250px;">
		    	<a href="{{chapter_instance.get_saq_list_url}}" ><img class="card-img-top" src="..." alt="Card image cap"></a>
		      <div class="card-body">
		        <a href="{{chapter_instance.get_saq_list_url}}" ><strong class="heading card-title">Short Answer Questions</p></strong>
		      </div>
		    </div>
		 </div>
		{% endif %}
		{% if numericals %}
		<div class="col-md-3 col-sm-4 ">
		    <div class="card mb-3" style="height: 250px;">
		    	<a href="{{chapter_instance.get_numerical_list_url}}" ><img class="card-img-top" src="..." alt="Card image cap"></a>
		    	<div class="card-body">
		        <a href="{{chapter_instance.get_numerical_list_url}}" ><strong class="heading card-title">Numerical Problems</p></strong>
		      </div>
		    </div>
		 </div>
	</div>
		{% endif %}
</div>
{%endblock content%}

cms/templates/cms/numerical_form.html
{%extends "base.html"%}
{% block headextra %}
{{ form.media }}
{% endblock headextra %}

{% load crispy_forms_tags %}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{chapter_instance.get_subject_select_from_chapter}}" >{{chapter_instance.subject}} </a> | <a href = "{{chapter_instance.get_chapter_select_url}}" >{{chapter_instance.chapter_name}} </a> | <a href = "{{chapter_instance.get_numerical_list_url}}"> Numericals </a>

{% endblock path %}

{% block content %}
<div class = 'col-sm-6 col-sm-offset-2'>
	<p>{{chapter_instance.chapter_name}}</p>
	<small>{{chapter_instance.subject}}</small>
	<form method = 'POST' action = '' enctype = 'multipart/form-data'>
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class= 'btn btn-default' value = "Okay"/>
	</form>
</div>
{%endblock content %}

cms/templates/cms/numerical_list.html
{% extends 'chapter_base.html' %}
{% load markdown_deux_tags %}
{% load static %}

{%block headmore%}
<link rel="stylesheet" type="text/css" href="{% static 'cms/css/numerical_detail.css' %}">
{%endblock headmore%}

{% block content %}
<div class="document">
	<div class="numerical-head alert" role="alert">
		<small>
			<div class="path">
				Path: <a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{chapter_instance.get_subject_select_from_chapter}}" >{{chapter_instance.subject}} </a> | <a href = "{{chapter_instance.get_chapter_select_url}}" >{{chapter_instance.chapter_name}} </a> | <a href = "{{chapter_instance.get_numerical_list_url}}"> Numericals </a>
			</div>
		</small>
		<h1 class='heading'> Numerical Problems and Solutions</h1>
		<p><a href="{{chapter_instance.get_numerical_create_url}}">Add new</a></p>
		<hr/>
	</div>

	<div class="numerical-list offset-sm-1 offset-md-1">
		{% for obj in numericals %}
		<div class = 'numerical-question heading'><h4>{{obj.numerical_serial}}. {{obj.question}}
			<a class="edit-link" href="{{obj.get_numerical_edit_url}}">Edit</a></h4>
		</div>
			<p><span class="badge-secondary remark"> {{obj.remarks}} </span></p>

			<div class = 'numerical-answer content'>{{obj.answer|markdown}}</div>
			<hr/>
		{%endfor%}
	</div>
</div>
{% endblock content %}

cms/templates/cms/saq_form.html
{%extends "base.html"%}
{% block headextra %}
{{ form.media }}
{% endblock headextra %}

{% load crispy_forms_tags %}

{% block path %}
 <a href="{% url 'cms:subject_list' %}"> Home </a> | <a href="{{chapter_instance.get_subject_select_from_chapter}}" >{{chapter_instance.subject}} </a> | <a href = "{{chapter_instance.get_chapter_select_url}}" >{{chapter_instance.chapter_name}} </a> | <a href = "{{chapter_instance.get_saq_list_url}}"> SAQs </a>
{% endblock path %}

{% block content %}
<div class = 'col-sm-6 col-sm-offset-2'>
	<p>{{chapter_instance.chapter_name}}</p>
	<small>{{chapter_instance.subject}}</small>
	<form method = 'POST' action = '' enctype = 'multipart/form-data'>
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class= 'btn btn-default' value = "Okay"/>
	</form>
</div>
{%endblock content %}

cms/templates/cms/subject_form.html
{%extends "base.html"%}
{% block content %}

{% load crispy_forms_tags %}

<div class = 'col-sm-6 col-sm-offset-2'>
	<form method = 'POST' action = '' enctype = 'multipart/form-data'>
	{% csrf_token %}
	{{form|crispy}}
	<input type="submit" class= 'btn btn-default' value = "Okay"/>
	</form>
</div>
{%endblock content %}

cms/templates/cms/subject_list.html
{% extends 'base.html' %}
{% load static %}

{% block headextra %}
	<link href="{% static 'cms/css/subject_list.css' %}" rel="stylesheet" type="text/css" >
	<link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">
{% endblock headextra %}

{%block content%}
<div class="document">
	<p><a href="{% url 'cms:subject_create' %}"> Create subject </a> </p>
	<div class="card-deck">
		{%for obj in subjects%}
		  <div class="col-md-4 col-sm-6">
		    <div class="card mb-3" style="height: 400px;">
		    	{%if obj.poster_image %}
		    	<a href="{{ obj.get_subject_select_url }}"> <img class="card-img-top img-fluid" src="{{obj.poster_thumbnail.url}}" alt="Card image cap"> </a>
		    	{%endif%}
		      <div class="card-body">
		        <a href="{{ obj.get_subject_select_url }}"> <h4 class="heading card-title"> {{obj.subject_name}}</h4> </a>
		        <small>Class: {{obj.grade}} </small>
		        <p class="card-text">{{obj.poster_text}}</p>
		      </div>
		    </div>
		  </div>
		{% endfor %}
	</div>
{%endblock content%}